name: CI

on: [push]

jobs:
  build:
    name: ci
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup Java JDK
      uses: actions/setup-java@v1
      with:
        java-version: 17
        
    - name: Change wrapper permissions
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
        jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv